//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.App_GlobalResources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string bairro {
            get {
                return ResourceManager.GetString("bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string cidade {
            get {
                return ResourceManager.GetString("cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string cpf {
            get {
                return ResourceManager.GetString("cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Criação.
        /// </summary>
        public static string data_criacao {
            get {
                return ResourceManager.GetString("data_criacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Emissão.
        /// </summary>
        public static string data_emissao {
            get {
                return ResourceManager.GetString("data_emissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string data_nascimento {
            get {
                return ResourceManager.GetString("data_nascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail para a Autenticação no Sistema.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} é um campo requerido..
        /// </summary>
        public static string erro_requerido {
            get {
                return ResourceManager.GetString("erro_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome .
        /// </summary>
        public static string nome_pessoa {
            get {
                return ResourceManager.GetString("nome_pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Imagens.
        /// </summary>
        public static string num_imagens {
            get {
                return ResourceManager.GetString("num_imagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Páginas.
        /// </summary>
        public static string num_paginas {
            get {
                return ResourceManager.GetString("num_paginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da Casa.
        /// </summary>
        public static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua ou Avenida.
        /// </summary>
        public static string rua {
            get {
                return ResourceManager.GetString("rua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha para a Autenticação no Sistema.
        /// </summary>
        public static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status do Contrato.
        /// </summary>
        public static string status_contrato {
            get {
                return ResourceManager.GetString("status_contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status do Pedido.
        /// </summary>
        public static string status_pedido {
            get {
                return ResourceManager.GetString("status_pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string telefone {
            get {
                return ResourceManager.GetString("telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone do Parceiro.
        /// </summary>
        public static string telefone_parceiro {
            get {
                return ResourceManager.GetString("telefone_parceiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Pessoa.
        /// </summary>
        public static string tipo_pessoa {
            get {
                return ResourceManager.GetString("tipo_pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Serviço.
        /// </summary>
        public static string tipo_servico {
            get {
                return ResourceManager.GetString("tipo_servico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Convidados.
        /// </summary>
        public static string total_convidados {
            get {
                return ResourceManager.GetString("total_convidados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Cobrado ao Cliente.
        /// </summary>
        public static string valor_cobrado_ao_cliente {
            get {
                return ResourceManager.GetString("valor_cobrado_ao_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor por Imagem Adicional.
        /// </summary>
        public static string valor_imagem {
            get {
                return ResourceManager.GetString("valor_imagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Produto.
        /// </summary>
        public static string valor_produto {
            get {
                return ResourceManager.GetString("valor_produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Serviço.
        /// </summary>
        public static string valor_servico {
            get {
                return ResourceManager.GetString("valor_servico", resourceCulture);
            }
        }
    }
}
