//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.App_GlobalResources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} é um campo requerido..
        /// </summary>
        public static string erro_requerido {
            get {
                return ResourceManager.GetString("erro_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Imagens.
        /// </summary>
        public static string num_imagens {
            get {
                return ResourceManager.GetString("num_imagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Páginas.
        /// </summary>
        public static string num_paginas {
            get {
                return ResourceManager.GetString("num_paginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor por Imagem Adicional.
        /// </summary>
        public static string valor_imagem {
            get {
                return ResourceManager.GetString("valor_imagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Produto.
        /// </summary>
        public static string valor_produto {
            get {
                return ResourceManager.GetString("valor_produto", resourceCulture);
            }
        }
    }
}
